# This workflow will build and deploy an Astro site to GitHub Pages
# Adapted from the Node.js CI template

name: Build and Deploy Astro to Pages

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Astro Site
    runs-on: ubuntu-latest

    # Removed the matrix strategy for simplicity in deployment
    # You can add it back if you need to build/test against multiple Node versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Specify a single Node version for the build/deploy

    - name: Install dependencies
      run: npm ci # Use npm ci for clean install in CI environments

    - name: Build Astro site
      # This will run your 'astro build' command and create the 'dist' folder
      run: npm run build

    # Remove the npm test step as it's not needed for deployment
    # - run: npm test

    - name: Upload Pages artifact
      # Upload the contents of the 'dist' folder for the deployment job
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist # The path to your built site output

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages # Use the special github-pages environment
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build # This job depends on the build job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # Uses the dedicated action for deploying to GitHub Pages
        uses: actions/deploy-pages@v4
